# Generated by Django 2.0.5 on 2018-05-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='影院名称')),
                ('province', models.CharField(max_length=20, verbose_name='省')),
                ('city', models.CharField(max_length=20, verbose_name='市')),
                ('district', models.CharField(max_length=20, verbose_name='区')),
                ('location', models.CharField(max_length=20, verbose_name='影院地址')),
                ('phone_number', models.CharField(max_length=20, verbose_name='影院电话')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema_Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='影票价格')),
                ('on_time', models.DateField(verbose_name='上映日期')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='手机号码')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('sex', models.CharField(max_length=1, verbose_name='性别')),
                ('birth', models.DateField(verbose_name='生日日期')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='电影名称')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='电影评分')),
                ('introduction', models.TextField(default='暂无简介', max_length=200, verbose_name='电影简介')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(default='2018-05-24 21:09:03', verbose_name='订单日期')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cinema_Movie')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Member')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='cinema_movie',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Movie'),
        ),
    ]
