# Generated by Django 2.0.5 on 2018-05-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='posters/default.jpg', upload_to='', verbose_name='电影海报'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate_people',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='评价人数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-05-30 10:10:58', verbose_name='订单日期'),
        ),
    ]
