# Generated by Django 2.0.5 on 2018-05-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='posters/default.jpg', upload_to='', verbose_name='电影海报'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-05-28 15:03:06', verbose_name='订单日期'),
        ),
    ]
