# Generated by Django 2.0.5 on 2018-05-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180530_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=3, verbose_name='电影评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate_people',
            field=models.IntegerField(default=0, max_length=10, verbose_name='评价人数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-05-30 10:10:55', verbose_name='订单日期'),
        ),
    ]
