# Generated by Django 2.0.5 on 2018-05-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180530_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='电影评分'),
        ),
    ]
