# Generated by Django 2.0.5 on 2018-05-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20180530_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate_people',
            field=models.IntegerField(default=0, verbose_name='评价人数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-05-30 14:02:57', verbose_name='订单日期'),
        ),
    ]
