# Generated by Django 2.0.5 on 2018-05-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180530_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-05-30 14:02:56', verbose_name='订单日期'),
        ),
    ]
