# Generated by Django 2.0.5 on 2018-06-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180528_1540'),
        ('backend', '0008_auto_20180530_1432'),
    ]

    operations = [
    ]
