# Generated by Django 2.0.5 on 2018-06-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_merge_20180603_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema_movie',
            name='stage',
            field=models.CharField(default='null', max_length=10, verbose_name='场次'),
        ),
        migrations.AddField(
            model_name='order',
            name='seat_col',
            field=models.IntegerField(default=0, verbose_name='座位列数'),
        ),
        migrations.AddField(
            model_name='order',
            name='seat_row',
            field=models.IntegerField(default=0, verbose_name='座位行数'),
        ),
        migrations.AddField(
            model_name='order',
            name='stage',
            field=models.CharField(default='null', max_length=10, verbose_name='场次'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-06-03 22:10:07', verbose_name='订单日期'),
        ),
    ]
