# Generated by Django 2.0.5 on 2018-06-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20180603_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-06-03 22:10:52', verbose_name='订单日期'),
        ),
    ]
