# Generated by Django 2.0.6 on 2018-06-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20180603_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='餐饮服务名称')),
                ('introduction', models.TextField(default='暂无简介', max_length=200, verbose_name='电影简介')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='餐饮供应商名称')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cinema')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-06-05 17:05:36', verbose_name='订单日期'),
        ),
        migrations.AddField(
            model_name='food_service',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Food_Supplier'),
        ),
    ]
