# Generated by Django 2.0.5 on 2018-06-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20180605_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='area',
            field=models.CharField(default='欧美亚', max_length=50, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='unknow', max_length=50, verbose_name='导演'),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=50, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='movie',
            name='len',
            field=models.CharField(default='unknow', max_length=50, verbose_name='片长'),
        ),
        migrations.AddField(
            model_name='movie',
            name='protagonist',
            field=models.CharField(default='unknow', max_length=50, verbose_name='主演'),
        ),
        migrations.AddField(
            model_name='movie',
            name='types',
            field=models.CharField(default='unknow', max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-06-23 21:09:35', verbose_name='订单日期'),
        ),
    ]
