# Generated by Django 2.0.6 on 2018-06-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20180623_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='cinema_photo',
            field=models.ImageField(default='cinema_photos/default.jpg', upload_to='', verbose_name='影院照片'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-06-30 18:06:01', verbose_name='订单日期'),
        ),
    ]
