# Generated by Django 2.0.5 on 2018-06-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20180630_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-06-30', verbose_name='订单日期'),
        ),
    ]
