# Generated by Django 2.0.5 on 2018-08-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20180630_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='salt',
            field=models.CharField(default='salt1234', max_length=50, verbose_name='盐'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default='2018-08-13', verbose_name='订单日期'),
        ),
    ]
