# Generated by Django 2.0.5 on 2018-08-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20180813_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=80, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='member',
            name='salt',
            field=models.CharField(default='salt1234', max_length=80, verbose_name='盐'),
        ),
    ]
